# Generated by Django 3.2.16 on 2023-02-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryoption',
            name='option',
        ),
        migrations.RemoveField(
            model_name='deliveryoption',
            name='region',
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='name',
            field=models.CharField(default='Standard Shipping', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.99, max_digits=6),
        ),
    ]
