# Generated by Django 3.2.16 on 2023-02-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_photo_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alt',
            field=models.CharField(default='', max_length=200),
        ),
    ]
