# Generated by Django 3.2.16 on 2023-02-23 17:56

from django.db import migrations


def set_null_profile_id(apps, schema_editor):
    Review = apps.get_model('shop', 'Review')
    Review.objects.filter(profile_id=None).update(profile=None)

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_review_profile'),
    ]

    operations = [
        migrations.RunPython(set_null_profile_id),
    ]
