# Generated by Django 3.2.16 on 2023-02-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_set_null_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
    ]
