# Generated by Django 3.2.16 on 2023-02-14 15:26

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
