# Generated by Django 3.2.16 on 2023-02-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_shipping_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
